/**
 * Barangays of Dasmariñas City, Cavite (75).
 * Reference: PhilAtlas / PSA (https://www.philatlas.com/luzon/r04a/cavite/dasmarinas.html)
 */
const BARANGAYS_RAW = [
  'Burol',
  'Burol I',
  'Burol II',
  'Burol III',
  'Datu Esmael',
  'Emmanuel Bergado I',
  'Emmanuel Bergado II',
  'Fatima I',
  'Fatima II',
  'Fatima III',
  'H-2',
  'Langkaan I',
  'Langkaan II',
  'Luzviminda I',
  'Luzviminda II',
  'Paliparan I',
  'Paliparan II',
  'Paliparan III',
  'Sabang',
  'Saint Peter I',
  'Saint Peter II',
  'Salawag',
  'Salitran I',
  'Salitran II',
  'Salitran III',
  'Salitran IV',
  'Sampaloc I',
  'Sampaloc II',
  'Sampaloc III',
  'Sampaloc IV',
  'Sampaloc V',
  'San Agustin I',
  'San Agustin II',
  'San Agustin III',
  'San Andres I',
  'San Andres II',
  'San Antonio de Padua I',
  'San Antonio de Padua II',
  'San Dionisio',
  'San Esteban',
  'San Francisco I',
  'San Francisco II',
  'San Isidro Labrador I',
  'San Isidro Labrador II',
  'San Jose',
  'San Juan',
  'San Lorenzo Ruiz I',
  'San Lorenzo Ruiz II',
  'San Luis I',
  'San Luis II',
  'San Manuel I',
  'San Manuel II',
  'San Mateo',
  'San Miguel',
  'San Miguel II',
  'San Nicolas I',
  'San Nicolas II',
  'San Roque',
  'San Simon',
  'Santa Cristina I',
  'Santa Cristina II',
  'Santa Cruz I',
  'Santa Cruz II',
  'Santa Fe',
  'Santa Lucia',
  'Santa Maria',
  'Santo Cristo',
  'Santo Niño I',
  'Santo Niño II',
  'Victoria Reyes',
  'Zone I',
  'Zone I-B',
  'Zone II',
  'Zone III',
  'Zone IV',
] as const;

export const DASMARINAS_BARANGAYS: string[] = [...BARANGAYS_RAW].sort((a, b) =>
  a.localeCompare(b, 'en', { sensitivity: 'base', numeric: true }),
);
